---
- name: "Configure network"
  hosts: "all"
  remote_user: "{{ remote_shell_user }}"
  become: true

  tasks:
    - name: Create a bridge interface
      nmcli:
        conn_name: br0
        ifname: br0
        type: bridge
        state: absent

    - name: Restart network manager
      systemd:
        name: NetworkManager
        state: restarted
