---
- name: Run jellyfin in docker
  hosts: all
  remote_user: "{{ remote_shell_user }}"

  tasks:
    - name: Jellyfin directory
      ansible.builtin.file:
        path: "/home/{{ remote_shell_user }}/jellyfin/{{ item.src }}"
        state: directory
        mode: '0755'
      loop:
        - { src: cache }
        - { src: config }

    - name: Jellyfin library directory
      ansible.builtin.file:
        path: "/home/{{ remote_shell_user }}/media_library"
        state: directory
        mode: '0755'

    - name: Create jellyfin container
      docker_container:
        name: jellyfin_main
        image: jellyfin/jellyfin
        recreate: true
        state: started
        user: "1000:105"
        privileged: "yes"
        devices:
          - "/dev/dri/renderD128:/dev/dri/renderD128:rwm"
          - "/dev/dri/card0:/dev/dri/card0:rwm"
        volumes:
          - "/home/{{ remote_shell_user }}/jellyfin/cache:/cache"
          - "/home/{{ remote_shell_user }}/jellyfin/config:/config"
          - "/home/{{ remote_shell_user }}/media_library:/media"
        restart_policy: unless-stopped
        labels:
          "traefik.enable": "true"
          "traefik.http.routers.jellyfin.rule": "Host(`jellyfin.{{ homelab_private_host }}`)"
          "traefik.http.routers.jellyfin.entrypoints": "https,http"
          "traefik.http.routers.jellyfin.tls": "true"
          "traefik.http.routers.jellyfin.tls.certresolver": "cloudflare"
          "traefik.http.services.jellyfin.loadbalancer.server.port": "8096"
        networks:
          - name: '{{ traefik_network }}'
